// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'GoldenCare does not support iOS. '
          'Supported platforms: Android, Web.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPv73xM2mVrMKP91i17yxej6d24tSUbXc',
    appId: '1:143097198020:web:1bfefba8807c95495b2091',
    messagingSenderId: '143097198020',
    projectId: 'golden-care-d4863',
    authDomain: 'golden-care-d4863.firebaseapp.com',
    storageBucket: 'golden-care-d4863.firebasestorage.app',
    measurementId: 'G-1E46FR6MEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0hNMRDfRO9X1rJ1Vw1d_ut-adYLgjfdI',
    appId: '1:143097198020:android:d87719bd3960d5275b2091',
    messagingSenderId: '143097198020',
    projectId: 'golden-care-d4863',
    storageBucket: 'golden-care-d4863.firebasestorage.app',
  );
}
