#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYSTORE_PATH="${ROOT_DIR}/goldencare-release.jks"
KEY_PROPERTIES_PATH="${ROOT_DIR}/key.properties"
SIGNING_ENV_PATH="${ROOT_DIR}/.env.android_signing"

FORCE=false

usage() {
  cat <<EOF
Usage: $0 [--force]

Options:
  --force    Regenerate keystore and overwrite existing signing files
  -h, --help Show this message
EOF
}

log() { echo "[generate_android_keystore] $*"; }
err() { echo "[generate_android_keystore][ERROR] $*" >&2; }

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --force) FORCE=true; shift 1 ;;
      -h|--help) usage; exit 0 ;;
      *) err "Unknown argument: $1"; usage; exit 1 ;;
    esac
  done
}

random_token() {
  local length="${1:-24}"
  local token
  token="$(tr -d '-' </proc/sys/kernel/random/uuid)"
  while [[ ${#token} -lt ${length} ]]; do
    token+="$(tr -d '-' </proc/sys/kernel/random/uuid)"
  done
  echo "${token:0:length}"
}

ensure_tooling() {
  if ! command -v keytool >/dev/null 2>&1; then
    err "keytool is required but not found on PATH. Install a JDK first."
    exit 2
  fi
}

generate_keystore() {
  local key_alias="goldencare_upload"
  local store_password
  local key_password
  local dname

  store_password="$(random_token 24)"
  # PKCS12 (default on modern JDKs) requires key/store password parity.
  key_password="${store_password}"
  dname="CN=Golden Care, OU=Mobile, O=Golden Care, L=Chandigarh, ST=Chandigarh, C=IN"

  log "Generating release keystore at ${KEYSTORE_PATH}"
  keytool -genkeypair -v \
    -keystore "${KEYSTORE_PATH}" \
    -alias "${key_alias}" \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10000 \
    -storepass "${store_password}" \
    -keypass "${key_password}" \
    -dname "${dname}"

  cat >"${KEY_PROPERTIES_PATH}" <<EOF
storePassword=${store_password}
keyPassword=${key_password}
keyAlias=${key_alias}
storeFile=$(basename "${KEYSTORE_PATH}")
EOF

  cat >"${SIGNING_ENV_PATH}" <<EOF
# Auto-generated by scripts/generate_android_keystore.sh
# Keep this file private.
STORE_PASSWORD=${store_password}
KEY_PASSWORD=${key_password}
KEY_ALIAS=${key_alias}
KEYSTORE_FILE=$(basename "${KEYSTORE_PATH}")
EOF

  chmod 600 "${KEY_PROPERTIES_PATH}" "${SIGNING_ENV_PATH}" || true

  log "Generated signing files:"
  log "- ${KEYSTORE_PATH}"
  log "- ${KEY_PROPERTIES_PATH}"
  log "- ${SIGNING_ENV_PATH}"
}

main() {
  parse_args "$@"
  ensure_tooling

  if [[ "${FORCE}" == "true" ]]; then
    rm -f "${KEYSTORE_PATH}" "${KEY_PROPERTIES_PATH}" "${SIGNING_ENV_PATH}"
  fi

  if [[ -f "${KEYSTORE_PATH}" && -f "${KEY_PROPERTIES_PATH}" ]]; then
    log "Keystore and key.properties already exist. Use --force to regenerate."
    exit 0
  fi

  generate_keystore
}

main "$@"
